#### ...13/8

In [7]:
import numpy as np

In [8]:
arr1=np.array([])          #create empty array
arr1

array([], dtype=float64)

In [19]:
my_list=[1,2.4,"hii",15,1.1]
print(my_list)
print(type(my_list))

[1, 2.4, 'hii', 15, 1.1]
<class 'list'>


In [20]:
a=np.array(my_list)     ##covert list into array

In [21]:
a

array(['1', '2.4', 'hii', '15', '1.1'], dtype='<U32')

In [12]:
type(a)    ## give type of a 

numpy.ndarray

In [18]:
a.dtype   ## give the type og data under a

dtype('<U32')

In [14]:
a.ndim     ## number of diamension in array __ rows in array

1

In [15]:
a.size  ## how many element prasent in array

5

In [20]:
a.shape  ##

(5,)

In [22]:
my_matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [24]:
import numpy as np
b=np.array(my_matrix)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
b.ndim

2

In [28]:
b.size

12

In [30]:
b.shape

(3, 4)

In [32]:
type(b)

numpy.ndarray

In [34]:
b.dtype

dtype('int32')

In [42]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,6,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  6,  9],
        [10, 11, 12]]])

In [46]:
arr1.shape

(2, 2, 3)

In [48]:
arr1.ndim

3

In [50]:
arr1.size

12

In [52]:
type(arr1)

numpy.ndarray

In [54]:
arr1.dtype

dtype('int32')

#### ....built in methods

#### ...reshape

In [60]:
arr2=arr1.reshape((1,3,4))

In [62]:
arr2.shape

(1, 3, 4)

In [64]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  6],
        [ 9, 10, 11, 12]]])

### ....arange

In [68]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [74]:
np.arange(100,2,-4)

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [76]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### .....zeros and ones

In [79]:
np.zeros(3)

array([0., 0., 0.])

In [83]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
np.ones(3)

array([1., 1., 1.])

In [88]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
np.ones((4,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#### .....linesapce

In [95]:
import numpy as np

In [99]:
np.linspace(1,15)   ##..default 50 observation
##  both start and end are included in array

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [101]:
np.linspace(5,25,100)     ## equally spaced 10 values

array([ 5.        ,  5.2020202 ,  5.4040404 ,  5.60606061,  5.80808081,
        6.01010101,  6.21212121,  6.41414141,  6.61616162,  6.81818182,
        7.02020202,  7.22222222,  7.42424242,  7.62626263,  7.82828283,
        8.03030303,  8.23232323,  8.43434343,  8.63636364,  8.83838384,
        9.04040404,  9.24242424,  9.44444444,  9.64646465,  9.84848485,
       10.05050505, 10.25252525, 10.45454545, 10.65656566, 10.85858586,
       11.06060606, 11.26262626, 11.46464646, 11.66666667, 11.86868687,
       12.07070707, 12.27272727, 12.47474747, 12.67676768, 12.87878788,
       13.08080808, 13.28282828, 13.48484848, 13.68686869, 13.88888889,
       14.09090909, 14.29292929, 14.49494949, 14.6969697 , 14.8989899 ,
       15.1010101 , 15.3030303 , 15.50505051, 15.70707071, 15.90909091,
       16.11111111, 16.31313131, 16.51515152, 16.71717172, 16.91919192,
       17.12121212, 17.32323232, 17.52525253, 17.72727273, 17.92929293,
       18.13131313, 18.33333333, 18.53535354, 18.73737374, 18.93

In [105]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [107]:
np.linspace(5,25,100, retstep=True)

(array([ 5.        ,  5.2020202 ,  5.4040404 ,  5.60606061,  5.80808081,
         6.01010101,  6.21212121,  6.41414141,  6.61616162,  6.81818182,
         7.02020202,  7.22222222,  7.42424242,  7.62626263,  7.82828283,
         8.03030303,  8.23232323,  8.43434343,  8.63636364,  8.83838384,
         9.04040404,  9.24242424,  9.44444444,  9.64646465,  9.84848485,
        10.05050505, 10.25252525, 10.45454545, 10.65656566, 10.85858586,
        11.06060606, 11.26262626, 11.46464646, 11.66666667, 11.86868687,
        12.07070707, 12.27272727, 12.47474747, 12.67676768, 12.87878788,
        13.08080808, 13.28282828, 13.48484848, 13.68686869, 13.88888889,
        14.09090909, 14.29292929, 14.49494949, 14.6969697 , 14.8989899 ,
        15.1010101 , 15.3030303 , 15.50505051, 15.70707071, 15.90909091,
        16.11111111, 16.31313131, 16.51515152, 16.71717172, 16.91919192,
        17.12121212, 17.32323232, 17.52525253, 17.72727273, 17.92929293,
        18.13131313, 18.33333333, 18.53535354, 18.7

### ...eye
### ...identity matrix

In [112]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

####..create an eye from zeros array

#### ....USe of copy function 

In [122]:
array2=([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
array2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [128]:
B=np.array(array2)

In [130]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [158]:
array2[:10]=30
array2

TypeError: can only assign an iterable

In [136]:
array1=([5,10,15,20,25])
array1

[5, 10, 15, 20, 25]

In [138]:
C=np.array(array1)

In [140]:
C

array([ 5, 10, 15, 20, 25])

In [144]:
array2=array1
array2

[5, 10, 15, 20, 25]

In [146]:
array2

[5, 10, 15, 20, 25]

In [152]:
array3=array2.copy()

In [154]:
array3

[5, 10, 15, 20, 25]

### ....rand number

In [161]:
import numpy as np

In [163]:
np.random.rand()

0.7092794950343102

In [165]:
np.random.rand(10)

array([0.45157194, 0.19677263, 0.70359191, 0.90918632, 0.74706616,
       0.69473915, 0.45978325, 0.25538255, 0.38294589, 0.86046185])

In [167]:
np.random.rand(10).reshape((2,5))

array([[0.1517137 , 0.41542395, 0.74269923, 0.88021719, 0.42008402],
       [0.22194004, 0.52382438, 0.31569321, 0.34125622, 0.78464179]])

### ...randn

In [172]:
array1

[5, 10, 15, 20, 25]

In [174]:
array1=np.random.randn(50)
array1

array([-1.17277125, -0.15290216, -1.03575472, -0.46274872, -0.23758706,
        1.62999327, -0.44014491,  0.30587569,  0.51141434, -0.86410509,
        0.24815234, -0.54050743, -1.34152645, -0.80904521,  0.29925422,
        0.12403251, -2.61876053, -0.6999425 , -1.85003833,  1.20211572,
        0.69365397,  1.06333195, -2.18131192, -1.46598763,  0.49970689,
        0.15413521, -0.93971824,  0.5129887 , -0.17480017,  0.93377123,
       -0.11437767,  0.0579022 , -0.19122195, -0.02966413,  1.76358013,
       -2.41419265, -0.51104005, -0.66171395, -1.74834693, -0.18371069,
        1.70461784,  1.14674465,  1.68929328, -1.62518969,  1.89031189,
       -0.56289033, -1.64969148, -0.62783032,  0.4876886 ,  0.11769148])

### ....randint

In [183]:
np.random.randint(10)

3

In [187]:
np.random.randint(1,100,10)

array([60, 16, 51, 52, 28, 92, 78, 36, 71, 60])

In [189]:
np.random.randint(40,60,50)

array([52, 49, 42, 48, 56, 50, 59, 52, 53, 42, 43, 58, 40, 52, 50, 40, 54,
       41, 53, 53, 44, 55, 40, 43, 50, 58, 47, 50, 47, 51, 41, 57, 42, 44,
       58, 50, 48, 58, 42, 56, 57, 48, 49, 47, 43, 52, 58, 45, 51, 58])