#### ...13/8

In [1]:
import numpy as np

In [3]:
## array can only accept same type of data

In [4]:
arr1=np.array([])          #create empty array
arr1

array([], dtype=float64)

In [5]:
my_list=[1,2,5,15,11]
print(my_list)
print(type(my_list))

[1, 2, 5, 15, 11]
<class 'list'>


In [6]:
a=np.array(my_list)     ##covert list into array

In [7]:
a

array([ 1,  2,  5, 15, 11])

In [8]:
type(a)    ## give type of a 

numpy.ndarray

In [9]:
## size ,shape, ndim only work with array

In [10]:
a.dtype   ## give the type of  data under a

dtype('int32')

In [11]:
a.ndim     ## number of diamension in array __ rows in array

1

In [12]:
a.size  ## how many element prasent in array

5

In [13]:
a.shape  ## give you the shape...no of rows and columns

(5,)

In [14]:
my_matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]  ##two dimensinal array
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [15]:
import numpy as np
b=np.array(my_matrix)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
b.ndim

2

In [17]:
b.size   ## No of element in "b" array that is 12

12

In [18]:
b.shape  # 3 row and 4 colum is there

(3, 4)

In [19]:
type(b)  

numpy.ndarray

In [20]:
b.dtype

dtype('int32')

In [21]:
arr1=np.array([[[1,2,3],[4,5,6]],  [[7,6,9],[10,11,12]]])   ## three dimensional array
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  6,  9],
        [10, 11, 12]]])

In [22]:
arr1.shape # two main row under that  two rows and three columns are given there

(2, 2, 3)

In [23]:
arr1.ndim

3

In [24]:
arr1.size   # element in arr is 12

12

In [25]:
type(arr1)

numpy.ndarray

In [26]:
arr1.dtype

dtype('int32')

#### ....built in methods

#### ...reshape

In [27]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  6,  9],
        [10, 11, 12]]])

In [28]:
arr2=arr1.reshape((1,3,4))   ## reshape to the arr1 ..

In [29]:
arr2.shape      # reshape multiplication must be the 12..that is the size of arr

(1, 3, 4)

In [30]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  6],
        [ 9, 10, 11, 12]]])

In [31]:
arr2=arr1.reshape((2,3,4))   ## size not a 12 so give the error

ValueError: cannot reshape array of size 12 into shape (2,3,4)

In [32]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  6],
        [ 9, 10, 11, 12]]])

In [33]:
arr2=arr1.reshape((2,3,2))

In [34]:
arr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  6],
        [ 9, 10],
        [11, 12]]])

In [35]:
arr2=arr1.reshape((6,2))

In [36]:
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  6],
       [ 9, 10],
       [11, 12]])

### ....arange

In [37]:
np.arange(15)   ## will help you to generate array within the given  range 
##end; default start at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
np.arange(2,5)   ## star :2   # end:5-1=4

array([2, 3, 4])

In [39]:
np.arange(2,3)

array([2])

In [40]:
np.arange(3,2)

array([], dtype=int32)

In [41]:
np.arange(100,2,-4)

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [42]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [43]:
a=np.arange(0,11,2)

In [44]:
a

array([ 0,  2,  4,  6,  8, 10])

In [53]:
b=a.reshape(3,2)

In [54]:
b

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [55]:
b.shape

(3, 2)

In [47]:
b=a.reshape(6)

In [48]:
b

array([ 0,  2,  4,  6,  8, 10])

In [49]:
b.shape

(6,)

In [50]:
b.shape

(6,)

In [51]:
b.shape

(6,)

In [ ]:
## for odd value there is only one condition that is (1,7) either(7,1)

### .....zeros and ones

..... zeros

In [79]:
np.zeros(3)   ## help you to generate only zeros ...and bydefault generate the floting point numbers

array([0., 0., 0.])

In [83]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
## if you want ot change the type then give the type

In [18]:
np.zeros(3,dtype=int)

array([0, 0, 0])

......ones

In [86]:
np.ones(3)        ## help you to generate only ones ...and bydefault generate the floting point numbers   

array([1., 1., 1.])

In [23]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.ones((4,5,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

#### .....linesapce       

In [ ]:
## linear space
## it return evenly spaced numbers over a specified  intervel.
## same as arrange function but it return the floting point numbers

In [28]:
import numpy as np

In [29]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [99]:
np.linspace(1,15)   ##..default 50 observation...when we not give the last value
##  both start and end are included in array   ## it give 

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [101]:
np.linspace(5,25,100)     ## equally spaced 100 values

array([ 5.        ,  5.2020202 ,  5.4040404 ,  5.60606061,  5.80808081,
        6.01010101,  6.21212121,  6.41414141,  6.61616162,  6.81818182,
        7.02020202,  7.22222222,  7.42424242,  7.62626263,  7.82828283,
        8.03030303,  8.23232323,  8.43434343,  8.63636364,  8.83838384,
        9.04040404,  9.24242424,  9.44444444,  9.64646465,  9.84848485,
       10.05050505, 10.25252525, 10.45454545, 10.65656566, 10.85858586,
       11.06060606, 11.26262626, 11.46464646, 11.66666667, 11.86868687,
       12.07070707, 12.27272727, 12.47474747, 12.67676768, 12.87878788,
       13.08080808, 13.28282828, 13.48484848, 13.68686869, 13.88888889,
       14.09090909, 14.29292929, 14.49494949, 14.6969697 , 14.8989899 ,
       15.1010101 , 15.3030303 , 15.50505051, 15.70707071, 15.90909091,
       16.11111111, 16.31313131, 16.51515152, 16.71717172, 16.91919192,
       17.12121212, 17.32323232, 17.52525253, 17.72727273, 17.92929293,
       18.13131313, 18.33333333, 18.53535354, 18.73737374, 18.93

In [105]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [58]:
np.linspace(1,5,5,retstep=True)

(array([1., 2., 3., 4., 5.]), 1.0)

In [107]:
np.linspace(5,25,100, retstep=True)  ##retstep tell the intervel(difference added) within this numbers ## below 0.20

(array([ 5.        ,  5.2020202 ,  5.4040404 ,  5.60606061,  5.80808081,
         6.01010101,  6.21212121,  6.41414141,  6.61616162,  6.81818182,
         7.02020202,  7.22222222,  7.42424242,  7.62626263,  7.82828283,
         8.03030303,  8.23232323,  8.43434343,  8.63636364,  8.83838384,
         9.04040404,  9.24242424,  9.44444444,  9.64646465,  9.84848485,
        10.05050505, 10.25252525, 10.45454545, 10.65656566, 10.85858586,
        11.06060606, 11.26262626, 11.46464646, 11.66666667, 11.86868687,
        12.07070707, 12.27272727, 12.47474747, 12.67676768, 12.87878788,
        13.08080808, 13.28282828, 13.48484848, 13.68686869, 13.88888889,
        14.09090909, 14.29292929, 14.49494949, 14.6969697 , 14.8989899 ,
        15.1010101 , 15.3030303 , 15.50505051, 15.70707071, 15.90909091,
        16.11111111, 16.31313131, 16.51515152, 16.71717172, 16.91919192,
        17.12121212, 17.32323232, 17.52525253, 17.72727273, 17.92929293,
        18.13131313, 18.33333333, 18.53535354, 18.7

### ...eye
### ...identity matrix

In [112]:
np.eye(5)      ## going to create identity matrix  ## matrix with diagonul elemnt is one and all zero...# cross 1 line
##bydefult floting pont number ...we can also use the identity here..#mostly use eye 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [64]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

####..create an eye from zeros array

In [65]:
z=np.zeros((5,5))

In [66]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
np.fill_diagonal(z,1)

In [69]:
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## broadcasting in array

In [70]:
big_one=np.ones((3,4))   ## accepting all element and perform operation on that is calld broadcasting
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
## we want to multiply all element by 5 ...above elemnt

In [71]:
big_one*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [73]:
bigger_one=big_one*6-2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [77]:
bigger=np.array(big_one*3-0.4,dtype="int")
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [78]:
int(0.4)

0

In [79]:
bigger.dtype

dtype('int32')

In [80]:
type(bigger)

numpy.ndarray

In [81]:
bigger.shape

(3, 4)

In [82]:
bigger/bigger

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
bigger//bigger

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [85]:
arr1=np.arange(3,20)  #3 to 19 numbers will be generated 
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [87]:
arr1+arr1   ## 3+3,4+4,5+5....

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [88]:
arr1**arr1  

array([         27,         256,        3125,       46656,      823543,
          16777216,   387420489,  1410065408,  1843829075,  -251658240,
       -1692154371, -1282129920,  1500973039,           0,  1681328401,
         457441280,  -306639989])

#### ....USe of copy function 

In [ ]:
## use generate backup or cpy of your array

In [100]:
import numpy as np

In [91]:
arr2=arr1   ## not recommended
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [102]:
arr2[:10]=30   ## using idexsing /sclicing to modify arr2
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 13, 14, 15, 16, 17, 18, 19])

In [103]:
arr1   ## here  aar1 (original) also change so we dont use the"=" sign ...## use the copy

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 13, 14, 15, 16, 17, 18, 19])

In [111]:
arr3=arr2.copy()
arr3                      ##generate a copy/ create a backup

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 13, 14, 15, 16, 17, 18, 19])

In [112]:
arr3[10:]=100
arr3

array([ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30, 100, 100, 100,
       100, 100, 100, 100])

In [113]:
arr2   ## here not chage in original

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 13, 14, 15, 16, 17, 18, 19])

In [114]:
arr1

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 13, 14, 15, 16, 17, 18, 19])

## .....

In [93]:
B=np.array(array2)

In [94]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [95]:
array2[:10]=30   ## using idexsing /sclicing to modify arr2
array2

TypeError: can only assign an iterable

In [105]:
array1=([5,10,15,20,25])
array1

[5, 10, 15, 20, 25]

In [106]:
C=np.array(array1)

In [107]:
C

array([ 5, 10, 15, 20, 25])

In [108]:
array2=array1
array2

[5, 10, 15, 20, 25]

In [152]:
array3=array2.copy()

In [154]:
array3

[5, 10, 15, 20, 25]

## #randum number generation

numpy also has lots of way to create a randum number arrays

### ....rand  fun

qs.... create an array of given shape and populate it with randam samples from the uniform distribution over [0 to 1]

In [116]:
np.random.rand()   # any number from o to 1 will be generated

0.6556593447855622

In [121]:
np.random.rand(10)  ## give the 10 values from 0 to on 1 ..# it give you the unifom distribution

array([0.81853218, 0.58208141, 0.57853386, 0.27977935, 0.50473786,
       0.05579729, 0.52269207, 0.44159695, 0.41787331, 0.24613019])

In [120]:
np.random.rand(10).reshape((2,5))

array([[0.69501349, 0.02994109, 0.85551132, 0.17904052, 0.11422718],
       [0.13036698, 0.25482406, 0.03947236, 0.38692199, 0.66480215]])

In [122]:
# create array from uniform distribution
new_array=np.random.rand(5,3)

# 2 dimessional array of shape(5,3)
new_array

array([[0.46996402, 0.83824574, 0.09065906],
       [0.75552589, 0.62655755, 0.83230577],
       [0.92821916, 0.62317155, 0.7529491 ],
       [0.12305054, 0.07623544, 0.31542862],
       [0.25051062, 0.1728545 , 0.15580474]])

## randn

Return a sample(or samples) from the "standerd normal distribution". unlike rand which is uniform   -3 to +3

In [ ]:
# for randn, random numbers generated will be approximately -3 to +3

In [172]:
array1

[5, 10, 15, 20, 25]

In [126]:
array1=np.random.randn(50)   # 50 observations from  std normal distribution
array1

array([-0.33825965,  1.10401194, -2.13908966,  0.54153036,  0.13021867,
        1.86737145,  0.84766673,  0.6725976 , -1.72850122, -0.53651533,
        1.2588791 ,  0.7682668 ,  0.56899808,  0.66416243,  0.02277262,
        0.3978578 ,  2.31342387,  1.13634365, -1.3114252 , -1.09513927,
        0.04028559, -0.69194698, -0.50996809, -1.94035605, -0.11832948,
        1.65073097, -0.10124037, -0.83399564,  0.81011334,  0.27401591,
       -0.93893279,  0.00289356, -1.36791288,  0.63936133, -1.82322962,
        0.69893964, -0.63120267, -1.23432107, -0.37591921, -0.58803257,
       -0.65992347, -0.54084531, -0.68393651,  0.87048544,  1.05758183,
       -0.92286551, -0.86486766, -0.50061913,  2.5052776 , -0.07052876])

In [128]:
max(array1)

2.505277602889379

In [129]:
min(array1)

-2.139089655724567

In [132]:
np.random.randn(2,2)

array([[ 0.87035002, -1.20588858],
       [-1.01023603, -1.91790869]])

In [138]:
np.random.randn(2,2,2)

array([[[-0.39524655,  0.51441049],
        [-0.41942478,  0.82573374]],

       [[-1.22406534, -0.25882522],
        [-1.24402245, -1.32906433]]])

### ....randint

return random integers from low (inclusive) to high(inclusive)

In [ ]:
## genereate you the randum integer

In [6]:
np.random.randint(1,100)
# third argument is no. of values. derfault = 1 value under 1 to 100

45

In [7]:
np.random.randint(1,100,10)

array([ 6, 75, 34, 65, 71, 33, 56, 40, 50, 60])

In [147]:
data=np.random.randint(40,60,50)    ## generater 50 value

In [150]:
data

array([59, 51, 48, 53, 43, 56, 43, 51, 57, 43, 52, 41, 57, 57, 46, 49, 46,
       55, 55, 46, 58, 40, 58, 41, 50, 51, 49, 58, 58, 50, 57, 44, 40, 53,
       51, 57, 56, 44, 56, 46, 49, 50, 57, 51, 51, 55, 44, 49, 57, 44])

In [ ]:
## what is mode of this  or  mostly repeted number fromm above
## to generated this we use scipy library

In [145]:
from scipy import stats

In [151]:
stats.mode(data)   ## whenever we generated it give different data

ModeResult(mode=57, count=7)

In [2]:
 a=np.array([[[[[[[[[[[1,2,3,4]]]]]]]]]]])
a.ndim

11

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [4]:
arr = np.arange(20)
ranarr = np.random.randint(0,100,10)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
ranarr

array([99, 36, 29,  8, 30,  5, 52, 20, 50,  3])

### max,min,argmax,argmin


These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [11]:
ranarr

array([99, 36, 29,  8, 30,  5, 52, 20, 50,  3])

In [12]:
ranarr.max()   ## highest element of the array

99

In [13]:
arr.max()

19

In [14]:
ranarr.min()  ## lowest element of the array

3

In [15]:
ranarr.argmax() ## Index location of highest element

0

In [16]:
ranarr.argmin() # Index location of lowest element  ## whenever duplicate value it take first accurence

9

In [17]:
ranarr.argmax()  # index location of highest element

0

In [18]:
ran2=ranarr.reshape(2,5)

In [19]:
ran2

array([[99, 36, 29,  8, 30],
       [ 5, 52, 20, 50,  3]])

In [20]:
ran2.max()

99

In [22]:
ran2.min()

3

In [23]:
ran2.argmax()

0

In [24]:
ran2.argmin()

9

## Happy learning