### ...14/08

# NumPy Indexing and Selection

Here we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
# creating simple array
arr=np.arange(0,21)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
## creating a simple array 
arr=np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [5]:
len(arr)

18

In [6]:
arr[-1]

95

In [7]:
#Get a value at an index
arr[9]

55

In [8]:
#Get values in a range
arr[1:11:2]  # give the value from 1 to 11 index with respect to second number

array([15, 25, 35, 45, 55])

### Filtering

In [9]:
import numpy as np

In [10]:
# filtering condition

In [11]:
arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [12]:
filterarr=arr<100   # give the which eelemnt satistsfied this condition and give true and false
filterarr

array([ True,  True, False,  True, False,  True,  True, False])

In [13]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False])

In [14]:
arr[arr<100]   ## we use the curly brackets to give that elemnt basis on that condition

array([ 1,  2,  4, 18, 71])

In [15]:
arr[5]

18

In [16]:
# where elemnt give you the index of that element which fatches thid condition as true

In [17]:
np.where(arr>100) # where function outputs index location of values
# meeting the condition

(array([2, 4, 7], dtype=int64),)

In [18]:
np.where(arr<100)

(array([0, 1, 3, 5, 6], dtype=int64),)

In [19]:
np.where(arr==100)  ## no elemnt so give the empty

(array([], dtype=int64),)

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. It is recommended to use the comma notation for clarity.

In [20]:
import numpy as np

In [21]:
arr_2=np.array([[1,2,3],[12,15,18],[64,96,128]])

In [22]:
arr_2

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [23]:
arr_2.dtype

dtype('int32')

In [24]:
arr_2[2,2]  ## give the second rows of second column 

128

In [25]:
arr_2[0,1]

2

In [26]:
arr_2[1,2]

18

In [27]:
arr_2[1:,:2]

array([[12, 15],
       [64, 96]])

In [28]:
arr_2[2,:2]  # it give the 2th row of two columns

array([64, 96])

In [30]:
arr_2[:1,:2]

array([[1, 2]])

In [32]:
arr_2[:2]

array([[ 1,  2,  3],
       [12, 15, 18]])

In [33]:
arr_2.shape

(3, 3)

In [34]:
arr_2[1]

array([12, 15, 18])

In [36]:
arr_2[:,2]

array([  3,  18, 128])

In [37]:
arr_2[1:,1:]

array([[ 15,  18],
       [ 96, 128]])

In [38]:
arr_2[1,1]

15

In [39]:
arr_2[0:2]

array([[ 1,  2,  3],
       [12, 15, 18]])

In [ ]:
# 2d array slicing

In [40]:
arr_2[:2,1:]

array([[ 2,  3],
       [15, 18]])

In [41]:
import numpy as np

In [43]:
arr=np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
arr1=arr.reshape(6,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [47]:
arr1[[2,1,4]] # select multiple row

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [49]:
arr1[:,[2,4]] ## 2,4 column

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19],
       [22, 24],
       [27, 29]])

In [50]:
arr1[[-1,1,4]]  ## nigative sclicing

array([[25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [52]:
arr1[[1,4,2],2:4]  # it give the 1,4,2 th row of 2,(4-1) column

array([[ 7,  8],
       [22, 23],
       [12, 13]])

In [54]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [57]:
arr1=np.ones((10,10))
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [58]:
arr1.shape

(10, 10)

In [60]:
## set up matrix
arr2d=np.zeros(arr1.shape)
arr2d##taking the shape of existing array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
arr2d.shape

(10, 10)

In [62]:
arr2d[[2,7]]  ## it give 2,7 column

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
no_of_rows=arr2d.shape[1]
no_of_rows

10

In [72]:
for j in range(11,21):
    print(j)

11
12
13
14
15
16
17
18
19
20


In [73]:
j=0
for i in range(no_of_rows):
    arr2d[i]=np.arange(j+1,j+11)
    j+=10
arr2d

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [77]:
a=np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [78]:
arr2d[[3,7]]

array([[31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
       [71., 72., 73., 74., 75., 76., 77., 78., 79., 80.]])

In [80]:
arr2d[[6,3,8]]

array([[61., 62., 63., 64., 65., 66., 67., 68., 69., 70.],
       [31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
       [81., 82., 83., 84., 85., 86., 87., 88., 89., 90.]])

In [81]:
arr2d[:,[2,4,6,8]]

array([[ 3.,  5.,  7.,  9.],
       [13., 15., 17., 19.],
       [23., 25., 27., 29.],
       [33., 35., 37., 39.],
       [43., 45., 47., 49.],
       [53., 55., 57., 59.],
       [63., 65., 67., 69.],
       [73., 75., 77., 79.],
       [83., 85., 87., 89.],
       [93., 95., 97., 99.]])

In [82]:
arr2d[[6,4,2,7]]

array([[61., 62., 63., 64., 65., 66., 67., 68., 69., 70.],
       [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
       [71., 72., 73., 74., 75., 76., 77., 78., 79., 80.]])

In [85]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [87]:
arr2d

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [88]:
arr2d[:,0]<40

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [89]:
np.where(arr2d[:,0]>40)

(array([4, 5, 6, 7, 8, 9], dtype=int64),)

In [92]:
arr2d[[4,5,6,7,8,9]]

array([[ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [93]:
arr2d[np.where(arr2d[:,0]>40)]  #it give rows  ## wrong

array([[ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [94]:
arr2d[np.where(arr2d[0,:]%2==0)]   ## not understnad this

array([[ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

## Happy learing!